=== Minisiia/XmlXsdPowerTool/src/main/java/xml_power_tool/powertool.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="power" type="powerType"/>
  <!-- Комплексный тип -->
  <xs:complexType name="tcType">
    <xs:sequence>
      <xs:element name="power_consumption">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Low"/>
            <xs:enumeration value="Medium"/>
            <xs:enumeration value="High"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="productivity">
        <xs:simpleType>
          <!-- Предельные значения -->
          <xs:restriction base="xs:integer">
              <xs:minInclusive value="1"/>
              <xs:maxInclusive value="220"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="autonomy">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Шаблон для элемента autonomy -->
            <xs:pattern value="(Yes|No)"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="power_toolType">
    <xs:sequence>
      <xs:element name="model">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="DrillMaster 5000"/>
            <xs:enumeration value="Jigsaw 2000"/>
            <xs:enumeration value="Angle Grinder Pro"/>
            <xs:enumeration value="Belt Sander Mini"/>
            <xs:enumeration value="Rotary Hammer"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="handy">
        <!-- Простой тип -->
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Single-hand"/>
            <xs:enumeration value="Double-hand"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="China"/>
            <xs:enumeration value="USA"/>
            <xs:enumeration value="Germany"/>
            <xs:enumeration value="Japan"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="tcType" name="tc"/>
      <xs:element name="material">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Plastic"/>
            <xs:enumeration value="Metal"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="powerType">
    <xs:sequence>
      <xs:element type="power_toolType" name="power_tool" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Minisiia/XmlXsdPowerTool/src/main/java/xml_power_tool/powertool.xml
<?xml version="1.0" encoding="UTF-8" ?>

<power xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation = "powertool.xsd">
    <power_tool>
        <model>DrillMaster 5000</model>
        <handy>Single-hand</handy>
        <origin>China</origin>
        <tc>
            <power_consumption>Low</power_consumption>
            <productivity>120</productivity>
            <autonomy>Yes</autonomy>
        </tc>
        <material>Plastic</material>
    </power_tool>
    <power_tool>
        <model>Jigsaw 2000</model>
        <handy>Double-hand</handy>
        <origin>USA</origin>
        <tc>
            <power_consumption>Medium</power_consumption>
            <productivity>90</productivity>
            <autonomy>No</autonomy>
        </tc>
        <material>Metal</material>
    </power_tool>
    <power_tool>
        <model>Angle Grinder Pro</model>
        <handy>Double-hand</handy>
        <origin>Germany</origin>
        <tc>
            <power_consumption>High</power_consumption>
            <productivity>70</productivity>
            <autonomy>No</autonomy>
        </tc>
        <material>Metal</material>
    </power_tool>
    <power_tool>
        <model>Belt Sander Mini</model>
        <handy>Single-hand</handy>
        <origin>Japan</origin>
        <tc>
            <power_consumption>Low</power_consumption>
            <productivity>180</productivity>
            <autonomy>Yes</autonomy>
        </tc>
        <material>Plastic</material>
    </power_tool>
    <power_tool>
        <model>Rotary Hammer</model>
        <handy>Double-hand</handy>
        <origin>China</origin>
        <tc>
            <power_consumption>High</power_consumption>
            <productivity>50</productivity>
            <autonomy>No</autonomy>
        </tc>
        <material>Metal</material>
    </power_tool>
</power>
